# Ghostty - macOS overrides
macos-option-as-alt = left
window-decoration = none

# Font size ajustado pra Retina (base config tem 7pt pro Linux)
font-size = 13

# Transparency
background-opacity = 0.85
