# Kitty - macOS overrides
# No macOS, titlebar-only mantém resize mas remove a barra de titulo
hide_window_decorations titlebar-only
macos_option_as_alt left

# Transparency & Blur
background_opacity 0.85
background_blur 32

# Font size ajustado pra Retina (base kitty.conf tem 7pt pro Linux)
font_size 13.0
